# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17H2pBLSSlGJ9yqeiUYlGg2wrfsnrJL8D
"""

import numpy as np

class LinearSVM:
    def __init__(self, learning_rate=0.001, lambda_par=0.01, n_iters=1000):
        self.lr = learning_rate
        self.lambda_par = lambda_par
        self.n_iters = n_iters
        self.w = None
        self.b = None

    def fit(self, X, y):
        n_samples, n_features = X.shape

        # Convert labels {0,1} → {-1,1} if needed
        y_ = np.where(y <= 0, -1, 1)

        # Initialize parameters
        self.w = np.zeros(n_features)
        self.b = 0

        # Gradient Descent
        for _ in range(self.n_iters):
            for idx, x_i in enumerate(X):
                condition = y_[idx] * (np.dot(self.w, x_i) - self.b) >= 1

                if condition:
                    # Only regularization term affects w
                    dw = 2 * self.lambda_par * self.w
                    self.w -= self.lr * dw
                else:
                    # Regularization + hinge loss gradient
                    dw = 2 * self.lambda_par * self.w - y_[idx] * x_i
                    db = y_[idx]

                    self.w -= self.lr * dw
                    self.b -= self.lr * db

    def predict(self, X):
        linear_output = np.dot(X, self.w) - self.b
        return np.sign(linear_output)

X = np.array([[2, 3],[3, 4],[-1, -2], [-2, -3]])

y = np.array([1, 1, 0, 0])

svm = LinearSVM(learning_rate=0.01, lambda_par=0.01, n_iters=1000)
svm.fit(X, y)

predictions = svm.predict(X)

print("Predictions:", predictions)